# Server
server.port=8080

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/ptut_db
spring.datasource.username=ptut_user
spring.datasource.password=motdepasse123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# CORS (pour le frontend Vue.js)
spring.mvc.cors.allowed-origins=http://localhost:5173

# JWT
app.jwt.secret=ptut_application_jwt_secret_key_2026_change_me_please
app.jwt.expiration=86400000

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
